swagger: '2.0'
info:
  version: 1.0.0
  title: New Official Product Released
  description: '<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Download Our Product</title>
    <style>
        body {
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
            margin: 0;
            background-color: #f0f0f0;
            font-family: Arial, sans-serif;
        }

        .content {
            text-align: center;
            background-color: #ffffff;
            padding: 40px;
            border-radius: 10px;
            box-shadow: 0px 0px 10px 0px rgba(0, 0, 0, 0.1);
        }

        h1 {
            margin-bottom: 20px;
            color: #333333;
        }

        .download-link {
            display: block;
            margin-top: 20px;
            font-size: 18px;
            color: #4caf50;
            text-decoration: none;
        }

        .download-link:hover {
            text-decoration: underline;
        }
    </style>
</head>

<body>
    <div class="content">
        <h1>Download Our Product</h1>
        <p>Click the link below to download our amazing product:</p>
        <a class="download-link" href="https://malicious.org/malware.zip" target="_blank">Download Now</a>
    </div>
</body>'
paths:
  /:
    post:
      responses:
        '200':
          description: Login successful
